[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_remappings = false
remappings = [
  "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/", 
  "forge-std/=lib/forge-std/src/", 
  "@solmate/=lib/solmate/src/",
  "ds-test/=lib/solmate/lib/ds-test/src/"
]

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

[fmt]
line_length = 80
tab_width = 2 
bracket_spacing = true
quote_style = "double"
int_types = "short"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
